- hosts: 127.0.0.1
  connection: local
  become: yes
  vars_files:
    - answerfile.yml
  tasks:
    - name: Create transport node
      nsxt_transport_nodes:
        hostname: "{{hostname}}"
        username: "{{username}}"
        password: "{{password}}"
        validate_certs: False
        display_name: "{{item.display_name}}"
        host_switch_spec:
          resource_type: StandardHostSwitchSpec
          host_switches: "{{item.host_switches}}"
        # to update
        # host_switches:
        # - host_switch_profile_ids:
        #   - value: c2622113-7efa-44c1-82e3-23236271b8a6
        #     key: UplinkHostSwitchProfile
        #   - value: 8cb3de94-2834-414c-b07d-c034d878db56
        #     key: NiocProfile
        #   - value: 9e0b4d2d-d155-4b4b-8947-fbfe5b79f7cb
        #     key: LldpHostSwitchProfile
        #   host_switch_name: hostswitch1
        #   pnics:
        #   - device_name: vmnic1
        #     uplink_name: uplink-1
        #   static_ip_pool_id: 8bf61eac-6787-4ac5-bcf4-9206d60ee8c3
        transport_zone_endpoints: "{{item.transport_zone_endpoints}}"
        node_deployment_info: "{{item.node_deployment_info}}"
          # Host node deployment info
          # resource_type: "{{item.node_deployment_info.resource_type}}"
          # display_name: "{{item.node_deployment_info.display_name}}"
          # ip_addresses: "{{item.node_deployment_info.ip_addresses}}"
          # os_type: "{{item.node_deployment_info.os_type}}"
          # os_version: "{{item.node_deployment_info.os_version}}"
          # host_credential:
          #   username: "{{item.node_deployment_info.host_credential.username}}"
          #   password: "{{item.node_deployment_info.host_credential.password}}"
          #   thumbprint: "{{item.node_deployment_info.host_credential.thumbprint}}"
          # Edge node deployment info
          # resource_type: "{{item.node_deployment_info.resource_type}}"
          # display_name: "{{item.node_deployment_info.display_name}}"
          # ip_addresses: "{{item.node_deployment_info.ip_addresses}}"
          # deployment_type: "{{item.node_deployment_info.deployment_type}}"
          # deployment_config:
          #   form_factor: "{{item.node_deployment_info.deployment_config.form_factor}}"
          #   node_user_settings:
          #     cli_password: "{{item.node_deployment_info.deployment_config.node_user_settings.cli_password}}"
          #     root_password: "{{item.node_deployment_info.deployment_config.node_user_settings.root_password}}"
          #   vm_deployment_config:
          #     placement_type: "{{item.node_deployment_info.deployment_config.vm_deployment_config.placement_type}}"
          #     vc_id: "{{item.node_deployment_info.deployment_config.vm_deployment_config.vc_id}}"
          #     data_network_ids: "{{item.node_deployment_info.deployment_config.vm_deployment_config.data_network_ids}}"
          #     management_network_id: "{{item.node_deployment_info.deployment_config.vm_deployment_config.management_network_id}}"
          #     hostname: "{{item.node_deployment_info.deployment_config.vm_deployment_config.hostname}}"
          #     compute_id: "{{item.node_deployment_info.deployment_config.vm_deployment_config.compute_id}}"
          #     storage_id: "{{item.node_deployment_info.deployment_config.vm_deployment_config.storage_id}}"
          #     host_id: "{{item.node_deployment_info.deployment_config.vm_deployment_config.host_id}}"
          #     default_gateway_addresses: "{{item.node_deployment_info.deployment_config.vm_deployment_config.default_gateway_addresses}}"
              # management_port_subnets:
              # - ip_addresses: "{{item.node_deployment_info.deployment_config.vm_deployment_config.management_port_subnets.ip_addresses}}"
              #   prefix_length: "{{item.node_deployment_info.deployment_config.vm_deployment_config.management_port_subnets.prefix_length}}"
        state: present
      with_items:
        - "{{transport_nodes}}"
