- hosts: 127.0.0.1
  connection: local
  become: yes
  vars_files:
    - answerfile.yml
  tasks:
    - name: Upload MUB to NSX-T Manager
      nsxt_upgrade_upload_mub_facts:
        hostname: "{{hostname}}"
        username: "{{username}}"
        password: "{{password}}"
        validate_certs: False
        bundle_id: "2500014166034"