# Copyright 2018 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause OR GPL-3.0-only
---
#
# Playbook to test Segment
#
- hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:
    - name: create Tier0
      nsxt_tier0:
        hostname: "10.160.84.49"
        username: "admin"
        password: "Admin!23Admin"
        validate_certs: False
        id: test-tier0
        display_name: test-tier0
        state: "present"
        ha_mode: "ACTIVE_STANDBY"
        failover_mode: "PREEMPTIVE"
        disable_firewall: True
        force_whitelisting: True
        tags:
          - scope: "a"
            tag: "b"
        t0ls_id: test-t0ls
        t0ls_state: "present"
        t0ls_display_name: "test-t0ls"
        t0ls_route_redistribution_types: ["TIER0_STATIC", "TIER0_NAT"]
        t0ls_edge_cluster_info:
          site_id: "default"
          enforcementpoint_id: "nsx"
          edge_cluster_id: "95196903-6b8a-4276-a7c4-387263e834fd"
        t0ls_preferred_edge_nodes_info:
          - site_id: "default"
            enforcementpoint_id: "nsx"
            edge_cluster_id: "95196903-6b8a-4276-a7c4-387263e834fd"
            edge_id: "940f1f4b-0317-45d4-84e2-b8c2394e7405"
        t0iface_id: "test-t0-t0ls-iface"
        t0iface_display_name: "test-t0-t0ls-iface"
        t0iface_state: "present"
        t0iface_subnets:
          - ip_addresses: ["35.1.1.1"]
            prefix_len: 24
        t0iface_segment_id: "sg-uplink"
        t0iface_edge_node_info:
          site_id: "default"
          enforcementpoint_id: "nsx"
          edge_cluster_id: "95196903-6b8a-4276-a7c4-387263e834fd"
          edge_id: "940f1f4b-0317-45d4-84e2-b8c2394e7405"